- name:
  block:
    - name: Generate redis7.slave.conf
      template:
        src: "{{ item.src }}.j2"
        dest: "{{ item.dest }}"
      loop:
        - { src: 'redis7.slave.conf', dest: '/etc/redis7.conf' }
#        - { src: 'redis7.service', dest: '/usr/lib/systemd/system/redis7.service' }
    
    - name: Restart redis7.service and daemon-reload
      ansible.builtin.service:
        state: restarted
        enabled: true
        daemon_reload: true
        name: "redis7.service"
  when: redisRole == 'slave'

