#- name: Deploy redis cluster
- include_tasks: install_redis.yml
# 只用install_redis.yml则只安装单机版，只用install_redis_slave.yml则会把已安装为单机版的redis改为slave；两个都用则直接部署为slave
- include_tasks: install_redis_slave.yml
#- include_tasks: install_package.yml
#- include_tasks: push_certs.yml
#- include_tasks: push_my_cnf.yml
#- include_tasks: start_bootstrap_node.yml
#- include_tasks: alter_root_password.yml
#- include_tasks: create_database.yml
#- include_tasks: start_other_nodes.yml

