#  可在debian和redhat系列的linux发行版安装，不用其它设置，程序会自动选择，在centos7及ubuntu22.04测试通过
#- hosts: sql
#  gather_facts: yes
#  vars:
#    http_port: 82

#  tasks:
- name: mv OpenStack-train.repo... to /tmp
  shell: "cd /etc/yum.repos.d/ && if [ -f CentOS-OpenStack-train.repo ];then mv CentOS-QEMU-EV.repo CentOS-Ceph-Nautilus.repo CentOS-NFS-Ganesha-28.repo CentOS-Storage-common.repo CentOS-OpenStack-train.repo /tmp && yum remove -y centos-release-openstack-train;fi"
  when: ansible_os_family == "RedHat"
#要把上方的仓库删除，否则对yum安装nginx有影响，装完，剧本start时会有报错，但不影响使用
#
- name: Add nginx repo
  yum_repository: 
    name: nginx-stable
    description: nginx stable repo
    baseurl: 'http://nginx.org/packages/centos/$releasever/$basearch/'
    gpgcheck: yes
    enabled: yes
    gpgkey: https://nginx.org/keys/nginx_signing.key
  tags:
    - add nginx repo
  when: ansible_os_family == "RedHat"

- name: Yum Install Nginx
  yum: name=nginx state=latest
  tags: install nginx
  when: ansible_os_family == "RedHat"
  ignore_errors: true

- name: apt install curl gnupg2 ca-certificates lsb-release ubuntu-keyring
  apt: name=curl,gnupg2,ca-certificates,lsb-release,ubuntu-keyring update_cache=yes state=latest
  when: ansible_os_family == "Debian"

- name: Import an official nginx signing key for UB
  shell: "curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg"
  when: ansible_os_family == "Debian"

- name: Add Nginx repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu {{ ansible_distribution_release }} nginx"

- name: apt install nginx
  apt: name=nginx update_cache=true state=latest
  when: ansible_os_family == "Debian"

- name: copy index.html to client
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    backup: yes

- name: start nginx service
  service:
    name: nginx
    state: started
    enabled: yes
#     - shell: /usr/sbin/nginx
#       args:
#         creates: /run/nginx.pid
#执行一个判断，当/run/nginx.pid存在时，就不再执行/usr/sbin/nginx

- name: ls default.conf
  shell: "ls /etc/nginx/conf.d/default.conf.original"
    #  shell: "ls /etc/nginx/conf.d/default.conf.original &>/dev/null"
  register: result
  ignore_errors: true
#  上下两条在ub22中测试不生效，但不影响使用
- name: mv default.conf
  shell: "mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.original"
  when: result is failure
    #  when: original is failure
  notify: restart nginx

- name: copy nignx configuration file to client
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nginx/conf.d/{{ item }}"
  loop:
    - minio.conf
    - www.st.com.conf
    - k8s.conf
  notify: restart nginx

#handlers:
#  - name: restart nginx
#    service: name=nginx state=restarted

