---
- hosts: allnode
#- hosts: allslave
#- hosts: ceph
#- hosts: controller
  remote_user: andy
  gather_facts: true
  vars_files:
    - group_vars/main.yml

  roles:
#    - role: init
#      tags: ["init"]
    - role: ceph-deploy-nautilus
      tags: ["ceph-deploy"]
#    - { role: ceph-deploy-nautilus, tags: 'untagged' }
# 我的目的是运行没有tags的task，经测试untagged无效

