---
#- hosts: allnode
- hosts: ub
#  remote_user: andy
  gather_facts: true
  ignore_errors: true
  vars_files:
    - group_vars/main.yml

  roles:
    - role: docker-apt
#      tags: ["docker-apt"]
#    - { role: ceph-deploy-nautilus, tags: 'untagged' }
# 我的目的是运行没有tags的task，经测试untagged无效

