#---
#- hosts: sql
#
#  tasks: 
- name: Add MariaDB.repo
  copy: src=MariaDB.repo dest=/etc/yum.repos.d 

- name: yum install mariadb
  yum: name={{ item }} state=latest
  with_items:
    - mariadb
    - mariadb-server
    - python2-PyMySQL

- name: copy openstack.cnf
  copy: src=../files/openstack.cnf dest=/etc/my.cnf.d/ force=yes
  notify: restart mariadb

- name: start mariadb
  service: name=mariadb state=started enabled=yes

#- name: secure script
#  script: secure_mysql.sh
#  tags: script
# new version don't support secure_mysql any more 

- name: secure script
  script: mariadb-secure-installation.sh
  tags: script
# mariadb-secure-installation.sh 脚本可以使用，但其中设置的密码不生效，因为这是新版本的特性

- name: allow root login remotely
  shell: mysql -p{{ dbRootPasswd }} -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'my@sql';"

