---
- hosts: 192.168.1.79
  ignore_errors: true
  vars:
#    - src_mysql: mysql-5.7.31-linux-glibc2.12-x86_64
    - src_mysql: mysql-8.0.21-linux-glibc2.12-x86_64
    - BASEDIR: /usr/local/mysql
    - DATADIR: /data/mysql_data
    - softName: mysql

  tasks:
  - name: stop service 
    shell: systemctl stop mysql && systemctl disable mysql && systemctl daemon-reload

  - name: remove python2-PyMySQL
    yum: name=python2-PyMySQL state=absent

  - name: Delete {{ softName }} user 
    user: name={{ softName }} state=absent remove=yes

  - name: delete files and dir
    file: path={{ item }} state=absent
    with_items: 
      - /etc/my.cnf
      - "/usr/local/{{ src_mysql }}"
      - "{{ BASEDIR }}"
      - "{{ DATADIR }}"
      - /etc/init.d/mysql
      - /etc/profile.d/mysql.sh
 
