---
- hosts: pxc
  ignore_errors: true
  tasks:

  - name: stop the third mysql.service
    service:
      name: mysql
      state: stopped
    when: role=='mysql3'
  
  - name: Pause for 3 seconds to stop the second mysql node
    pause: seconds=3

  - name: stop the second mysql.service
    service:
      name: mysql
      state: stopped
    when: role=='mysql2'
  
  - name: Pause for 3 seconds to stop the bootstrap mysql node
    pause: seconds=3
  
  - name: stop mysql@bootstrap.service
    service: name=mysql@bootstrap.service state=stopped
    when: role=='bootstrap'

  - name: Remove pxc package
    yum: name='Percona-XtraDB-Cluster-57,Percona-XtraDB-Cluster-shared-57,Percona-XtraDB-Cluster-server-57,Percona-XtraDB-Cluster-client-57' state=absent
#    yum: name=percona-xtradb-cluster state=absent

  - name: Remove socat perl-DBD-MySQL percona-xtrabackup-24 qpress
    ansible.builtin.yum:
      name:
        - socat
        - perl-DBD-MySQL
        - percona-xtrabackup-24
        - qpress
        - percona-xtradb-cluster-shared-compat
        - percona-xtradb-cluster-client
        - percona-xtradb-cluster-shared
        - Percona-Server-shared-56
      state: absent

  - name: rpm -e --nodeps percona-release
    shell: "rpm -e --nodeps percona-release"

  - name: Find /etc/yum.repos.d/percona*
    find:
      paths: /etc/yum.repos.d
      file_type: file
      use_regex: yes
      patterns: '^percona.*'
    register: perconaFile

  - name: Delete /etc/yum.repos.d/percona*
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: 
#    loop:
      - "{{ perconaFile.files }}"

  - name: Delete /var/lib/mysql
    file:
      path: "{{ item }}"
      state: absent
    with_items: 
#    loop:
      - "/etc/my.cnf"
      - "/var/lib/mysql"
      - "/var/log/mysqld.log"
