- name: deliver root authorized_keys
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ lookup('file', '{{ item.dest }}/.ssh/id_rsa.pub') }}"
    state: present
  loop:
    - { user: 'root', dest: '/root' }
#    - { user: 'andy', dest: '/home/andy' }
- name: Create Normal User andy
  user: name=andy password={{'cf' | password_hash('sha512')}} state=present 

- name: deliver andy authorized_keys
  authorized_key:
    user: andy
    key: "{{ lookup('file', '/home/andy/.ssh/id_rsa.pub') }}"

- name: Append andy to /etc/sudoers
  lineinfile: path=/etc/sudoers line='andy ALL=(ALL) NOPASSWD:ALL' backup=true

- name: yum install sshpass
  yum: name=sshpass

- name: Generate all node's root ssh-keygen
  shell: '[ -f ~/.ssh/id_rsa ] || ssh-keygen -t rsa -q -N "" -f ~/.ssh/id_rsa'

- name: All nodes sshpass -pcf ssh-copy-id -o StrictHostKeyChecking=no all nodes
#  shell: "for i in 1 2;do sshpass -pcf ssh-copy-id -o StrictHostKeyChecking=no master$i;done"
  shell: "for i in 1 2 3;do sshpass -pcf ssh-copy-id -o StrictHostKeyChecking=no ha$i;done"
#  when: ansible_fqdn == 'controller.st.cn'

- name: All nodes sshpass -pcf ssh-copy-id -o StrictHostKeyChecking=no all nodes
#  shell: "for i in 1 2;do sshpass -pcf ssh-copy-id -o StrictHostKeyChecking=no master$i;done"
  shell: "for i in controller pxc2 pxc3;do sshpass -pcf ssh-copy-id -o StrictHostKeyChecking=no $i;done"
