---
- hosts: all
  tasks:

  - name: Get ip and gateway
#   debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
#    debug: msg="{{ ansible_default_ipv4['address'],ansible_default_ipv4['gateway'] }}"
    debug: msg="{{ ansible_default_ipv4.address,ansible_default_ipv4['gateway'] }}"

  - name: Get netmask and network
    debug: msg="{{ ansible_default_ipv4['netmask'],ansible_default_ipv4['network'] }}"

  - name: Get interface and macaddress
    debug: msg="{{ ansible_default_ipv4['interface'],ansible_default_ipv4['macaddress'] }}"


