---
- hosts: sql
  vars:
#    - BASEDIR: /usr/local/mysql
#    - softName: httpd
    - softName: openstack-dashboard
    - softName1: httpd

  tasks:
#  - name: stop {{ softName }} service 
#    shell: systemctl stop {{ softName }} && systemctl disable {{ softName }} && systemctl daemon-reload
#    service: name={{ softName }} state=stopped 

  - name: yum remove {{ softName }}
    yum: name="{{ softName }},{{ softName1 }}" state=absent 

#  - name: Delete {{ softName }} user 
#    user: name={{ softName }} state=absent remove=yes

  - name: Delete apache user 
    user: name=apache state=absent remove=yes

  - name: delete {{ softName }}/{{ softName1 }} files and dir
    file: path={{ item }} state=absent
    with_items: 
      - "/etc/openstack-dashboard"
      - "/usr/share/openstack-dashboard"
      - /etc/httpd/
      - /var/log/httpd
      - /usr/share/doc/httpd-tools-2.4.6
      - /usr/share/doc/python2-django-horizon-16.2.2/openstack-dashboard-httpd-logging.conf
      - /usr/share/texlive/licenses/apache2.txt
      - /usr/share/doc/python2-pyroute2-0.5.6/LICENSE.Apache.v2
      - /usr/share/doc/wqy-microhei-fonts-0.2.0/LICENSE_Apache2.txt
